import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { ConfigProvider } from 'antd'
import ClientLayout from '@/components/ClientLayout'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Tyre Management System',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ConfigProvider
          theme={{
            components: {
              Breadcrumb: {
                itemColor: '#fff',
                lastItemColor: 'dodgerblue',
                separatorColor: '#fff'
              }
            }
          }}
        >
          <ClientLayout>{children}</ClientLayout>
        </ConfigProvider>
      </body>
    </html>
  )
}
